runtime: nodejs16
instance_class: F2
inbound_services:
  - warmup
automatic_scaling:
  min_instances: 1
  min_pending_latency: 5000ms
  max_concurrent_requests: 80
  target_cpu_utilization: 0.8

env_variables:
  PORT: 8080
